export interface Country {
  code: string;
  name: string;
  flag: string;
}

// Nager.Date supported countries — most common first, then alphabetical
export const COUNTRIES: Country[] = [
  { code: 'PH', name: 'Philippines',        flag: '🇵🇭' },
  { code: 'US', name: 'United States',       flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom',      flag: '🇬🇧' },
  { code: 'AU', name: 'Australia',           flag: '🇦🇺' },
  { code: 'CA', name: 'Canada',              flag: '🇨🇦' },
  { code: 'SG', name: 'Singapore',           flag: '🇸🇬' },
  { code: 'JP', name: 'Japan',               flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea',         flag: '🇰🇷' },
  { code: 'IN', name: 'India',               flag: '🇮🇳' },
  { code: 'AE', name: 'United Arab Emirates',flag: '🇦🇪' },
  { code: 'DE', name: 'Germany',             flag: '🇩🇪' },
  { code: 'FR', name: 'France',              flag: '🇫🇷' },
  { code: 'IT', name: 'Italy',               flag: '🇮🇹' },
  { code: 'ES', name: 'Spain',               flag: '🇪🇸' },
  { code: 'NL', name: 'Netherlands',         flag: '🇳🇱' },
  { code: 'PT', name: 'Portugal',            flag: '🇵🇹' },
  { code: 'CH', name: 'Switzerland',         flag: '🇨🇭' },
  { code: 'SE', name: 'Sweden',              flag: '🇸🇪' },
  { code: 'NO', name: 'Norway',              flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark',             flag: '🇩🇰' },
  { code: 'FI', name: 'Finland',             flag: '🇫🇮' },
  { code: 'PL', name: 'Poland',              flag: '🇵🇱' },
  { code: 'AT', name: 'Austria',             flag: '🇦🇹' },
  { code: 'BE', name: 'Belgium',             flag: '🇧🇪' },
  { code: 'IE', name: 'Ireland',             flag: '🇮🇪' },
  { code: 'NZ', name: 'New Zealand',         flag: '🇳🇿' },
  { code: 'ZA', name: 'South Africa',        flag: '🇿🇦' },
  { code: 'BR', name: 'Brazil',              flag: '🇧🇷' },
  { code: 'MX', name: 'Mexico',              flag: '🇲🇽' },
  { code: 'AR', name: 'Argentina',           flag: '🇦🇷' },
  { code: 'CL', name: 'Chile',               flag: '🇨🇱' },
  { code: 'CO', name: 'Colombia',            flag: '🇨🇴' },
  { code: 'CN', name: 'China',               flag: '🇨🇳' },
  { code: 'HK', name: 'Hong Kong',           flag: '🇭🇰' },
  { code: 'TW', name: 'Taiwan',              flag: '🇹🇼' },
  { code: 'TH', name: 'Thailand',            flag: '🇹🇭' },
  { code: 'MY', name: 'Malaysia',            flag: '🇲🇾' },
  { code: 'ID', name: 'Indonesia',           flag: '🇮🇩' },
  { code: 'VN', name: 'Vietnam',             flag: '🇻🇳' },
  { code: 'NG', name: 'Nigeria',             flag: '🇳🇬' },
  { code: 'KE', name: 'Kenya',               flag: '🇰🇪' },
  { code: 'GH', name: 'Ghana',               flag: '🇬🇭' },
  { code: 'EG', name: 'Egypt',               flag: '🇪🇬' },
  { code: 'SA', name: 'Saudi Arabia',        flag: '🇸🇦' },
  { code: 'RU', name: 'Russia',              flag: '🇷🇺' },
  { code: 'UA', name: 'Ukraine',             flag: '🇺🇦' },
  { code: 'GR', name: 'Greece',              flag: '🇬🇷' },
  { code: 'CZ', name: 'Czech Republic',      flag: '🇨🇿' },
  { code: 'RO', name: 'Romania',             flag: '🇷🇴' },
  { code: 'HU', name: 'Hungary',             flag: '🇭🇺' },
];
