/**
 * lib/recurrence.ts
 * Client-side RRULE expansion for PlanIQ.
 *
 * Supports the subset generated by the Add Schedule form:
 *   FREQ=DAILY
 *   FREQ=WEEKLY
 *   FREQ=WEEKLY;BYDAY=MO,WE,FR   (custom days)
 *   FREQ=MONTHLY
 *   FREQ=YEARLY
 *   + optional UNTIL=YYYYMMDDTHHMMSSZ suffix
 *
 * Occurrences are returned as Date objects (UTC-based, preserving original
 * time-of-day so local formatting works correctly).
 */

import type { Schedule } from '@/types/database';

// ── Extended display type (virtual occurrences add extra fields) ──────────────
export interface DisplaySchedule extends Omit<Schedule, 'id'> {
  id: string;
  _is_virtual?: boolean;      // true for generated occurrences (not DB rows)
  _occurrence_date?: string;  // YYYY-MM-DD of this occurrence (virtual only)
  _base_id?: string;          // id of the parent recurring schedule (virtual only)
}

// ── Per-occurrence completion ─────────────────────────────────────────────────
/** Details of a single completed occurrence (from the schedule_completions table). */
export interface CompletionInfo { completed_at: string | null; days_late: number | null }
/** Map key: `${schedule_id}|${YYYY-MM-DD}` → completion info (present iff completed). */
export type CompletionMap = Map<string, CompletionInfo>;

export function completionKey(scheduleId: string, occurrenceDate: string): string {
  return `${scheduleId}|${occurrenceDate}`;
}

// ── Helpers ───────────────────────────────────────────────────────────────────
const DAY_MS = 86_400_000;

const DAY_CODE: Record<string, number> = {
  SU: 0, MO: 1, TU: 2, WE: 3, TH: 4, FR: 5, SA: 6,
};

function parseUntil(until: string): Date {
  // YYYYMMDDTHHMMSSZ or YYYYMMDD
  const y = until.slice(0, 4), m = until.slice(4, 6), d = until.slice(6, 8);
  return new Date(`${y}-${m}-${d}T23:59:59Z`);
}

function addMonths(date: Date, n: number): Date {
  const d = new Date(date);
  d.setUTCMonth(d.getUTCMonth() + n);
  return d;
}

function addYears(date: Date, n: number): Date {
  const d = new Date(date);
  d.setUTCFullYear(d.getUTCFullYear() + n);
  return d;
}

// ── Main expander ─────────────────────────────────────────────────────────────
/**
 * Expand a recurring schedule into virtual DisplaySchedule occurrences
 * that fall within [rangeStart, rangeEnd].
 *
 * The *base* occurrence (the actual DB row's date) is NOT included — it
 * is already present in the regular schedule list.  Only additional
 * occurrences are returned.
 */
export function expandRecurring(
  base: Schedule,
  rangeStart: Date,
  rangeEnd: Date,
  completions?: CompletionMap,
): DisplaySchedule[] {
  const rule = base.recurrence_rule;
  if (!rule) return [];

  // Parse RRULE parts
  const parts: Record<string, string> = {};
  rule.split(';').forEach(p => {
    const eq = p.indexOf('=');
    if (eq > 0) parts[p.slice(0, eq)] = p.slice(eq + 1);
  });

  const freq = parts['FREQ'];
  if (!freq) return [];

  // UNTIL from rule or recurrence_end column
  let until: Date | null = null;
  if (parts['UNTIL']) until = parseUntil(parts['UNTIL']);
  if (base.recurrence_end) {
    const re = new Date(base.recurrence_end + 'T23:59:59Z');
    if (!until || re < until) until = re;
  }

  // BYDAY → array of day numbers (0=SU … 6=SA)
  const byDayNums: number[] = (parts['BYDAY'] ?? '')
    .split(',')
    .map(d => DAY_CODE[d.trim().toUpperCase()])
    .filter(n => n !== undefined) as number[];

  // Excluded dates set (from future "skip this occurrence" feature)
  const excludedDates = new Set<string>(
    base.excluded_dates
      ? (typeof base.excluded_dates === 'string'
        ? JSON.parse(base.excluded_dates)
        : base.excluded_dates)
      : [],
  );

  // Event duration so end_time tracks correctly
  const startMs  = new Date(base.start_time).getTime();
  const endMs    = base.end_time ? new Date(base.end_time).getTime() : null;
  const duration = endMs != null ? endMs - startMs : null;

  const baseDateStr = base.start_time.slice(0, 10);
  const results: DisplaySchedule[] = [];

  // ── Generate occurrence dates ────────────────────────────────────────────
  const occurrenceDates: Date[] = [];
  const LIMIT = 800; // safety cap (> 2 years daily)

  let cur = new Date(base.start_time); // start from the base occurrence

  if (freq === 'DAILY') {
    cur = new Date(cur.getTime() + DAY_MS); // skip base
    while (cur <= rangeEnd && occurrenceDates.length < LIMIT) {
      if (until && cur > until) break;
      occurrenceDates.push(new Date(cur));
      cur = new Date(cur.getTime() + DAY_MS);
    }

  } else if (freq === 'WEEKLY' && byDayNums.length > 0) {
    // Custom: iterate each day, check if it's a selected weekday
    cur = new Date(cur.getTime() + DAY_MS); // skip base day
    while (cur <= rangeEnd && occurrenceDates.length < LIMIT) {
      if (until && cur > until) break;
      if (byDayNums.includes(cur.getUTCDay())) {
        occurrenceDates.push(new Date(cur));
      }
      cur = new Date(cur.getTime() + DAY_MS);
    }

  } else if (freq === 'WEEKLY') {
    cur = new Date(cur.getTime() + 7 * DAY_MS); // skip base week
    while (cur <= rangeEnd && occurrenceDates.length < LIMIT) {
      if (until && cur > until) break;
      occurrenceDates.push(new Date(cur));
      cur = new Date(cur.getTime() + 7 * DAY_MS);
    }

  } else if (freq === 'MONTHLY') {
    cur = addMonths(cur, 1); // skip base month
    while (cur <= rangeEnd && occurrenceDates.length < LIMIT) {
      if (until && cur > until) break;
      occurrenceDates.push(new Date(cur));
      cur = addMonths(cur, 1);
    }

  } else if (freq === 'YEARLY') {
    cur = addYears(cur, 1); // skip base year
    while (cur <= rangeEnd && occurrenceDates.length < LIMIT) {
      if (until && cur > until) break;
      occurrenceDates.push(new Date(cur));
      cur = addYears(cur, 1);
    }
  }

  // ── Filter to range + build DisplaySchedule objects ──────────────────────
  for (const d of occurrenceDates) {
    const dateStr = d.toISOString().slice(0, 10);
    if (d < rangeStart) continue; // before view window
    if (dateStr === baseDateStr) continue; // same day as base (dedup)
    if (excludedDates.has(dateStr)) continue; // skipped occurrence

    const occEnd = duration != null
      ? new Date(d.getTime() + duration).toISOString()
      : null;

    const comp = completions?.get(completionKey(base.id, dateStr));

    results.push({
      ...base,
      start_time:       d.toISOString(),
      end_time:         occEnd,
      // Per-occurrence completion (not the base row's is_completed)
      is_completed:     !!comp,
      completed_at:     comp?.completed_at ?? null,
      days_late:        comp?.days_late ?? null,
      _is_virtual:      true,
      _occurrence_date: dateStr,
      _base_id:         base.id,
      // Give a stable unique-ish key for React
      id:               `${base.id}_${dateStr}`,
    } as DisplaySchedule);
  }

  return results;
}

/**
 * Given a list of raw DB schedules (which may include recurring ones
 * that started before the current month), expand all recurring schedules
 * and return a merged list of DisplaySchedule objects sorted by start_time.
 *
 * The base row (original DB occurrence) is always included as-is.
 * Virtual occurrences are merged in alongside it.
 */
export function buildDisplaySchedules(
  schedules: Schedule[],
  rangeStart: Date,
  rangeEnd: Date,
  completions?: CompletionMap,
): DisplaySchedule[] {
  // Base rows. For a recurring schedule, its own row is the FIRST occurrence —
  // tag it with _base_id/_occurrence_date and source its completion from the
  // per-occurrence map (not the base row's is_completed column).
  const base = schedules.map(s => {
    if (s.recurrence_rule) {
      const dateStr = s.start_time.slice(0, 10);
      const comp = completions?.get(completionKey(s.id, dateStr));
      return {
        ...s,
        is_completed:     !!comp,
        completed_at:     comp?.completed_at ?? null,
        days_late:        comp?.days_late ?? null,
        _base_id:         s.id,
        _occurrence_date: dateStr,
      } as DisplaySchedule;
    }
    return { ...s } as DisplaySchedule;
  });
  const virtual: DisplaySchedule[] = [];

  for (const s of schedules) {
    if (s.recurrence_rule) {
      virtual.push(...expandRecurring(s, rangeStart, rangeEnd, completions));
    }
  }

  return [...base, ...virtual].sort(
    (a, b) => new Date(a.start_time).getTime() - new Date(b.start_time).getTime(),
  );
}
